# Generated by Django 2.1.3 on 2018-11-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='full_name')),
                ('sex', models.IntegerField(choices=[(1, 'male'), (2, 'girl'), (0, 'unknown')], verbose_name='gender')),
                ('profession', models.CharField(max_length=128, verbose_name='profession')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('qq', models.CharField(max_length=128, verbose_name='qq')),
                ('phone', models.CharField(max_length=128, verbose_name='phone')),
                ('status', models.IntegerField(choices=[(0, 'applicating'), (1, 'pass'), (2, 'fail')], verbose_name='current_status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
            ],
            options={
                'verbose_name': 'student info',
                'verbose_name_plural': 'student info',
            },
        ),
    ]
